### ISSUE TITLE
No library provided by hoogle package, just executable

### ISSUE THREAD

**Issue by mgsloan** [ndmitchell/hoogle#165]
In `stackage-server`, we use hoogle as a library - https://github.com/fpco/stackage-server/blob/1fbaf1357482ccf3e0033ff62332f9853a5594bc/Handler/Hoogle.hs .  While it's understood that updating to hoogle 5 will require some changes due to API differences, is it possible expose the library?  We'd appreciate it! Otherwise we will need to come up with some other approach to integrating hoogle.

I looked for an existing issue and found https://github.com/ndmitchell/hoogle/issues/118 , which probably should also be addressed.

**Comment by ndmitchell** [comment]
Yep, will do - and thanks for the pointer to where you use it - that should make it much easier to construct a sensible API that meets your needs.

**Comment by mgsloan** [comment]
Cool, sounds great to me!

**Comment by ndmitchell** [comment]
There's now a library, API is:

```
module Hoogle where

-- | Database containing Hoogle search data.
data Database

-- | Load a database from a file.
withDatabase :: FilePath -> (Database -> IO ()) -> IO ()

-- | Search a database, given a query string, produces a list of results.
searchDatabase :: Database -> String -> [Target]

data Target = Target
    {targetURL :: URL -- ^ URL where this thing is located
    ,targetPackage :: Maybe (String, URL) -- ^ Name and URL of the package it is in (Nothing if it is a package)
    ,targetModule :: Maybe (String, URL) -- ^ Name and URL of the module it is in (Nothing if it is a package or module)
    ,targetType :: String -- ^ One of package, module or empty string
    ,targetItem :: String -- ^ HTML span of the item, using <0> for the name and <1> onwards for arguments
    ,targetDocs :: String -- ^ HTML documentation to show, a sequence of block level elements
    } deriving (Show,Eq,Ord)

type URL = String
```

That looks like it actually covers all your use cases - does it look at least slightly plausible?

**Comment by snoyberg** [comment]
That looks great. Would it be possible to also provide an API for creating a new database from a set of .txt files?

**Comment by ndmitchell** [comment]
@snoyberg I was going to provide an API `hoogle :: [String] -> IO ()` which is just the command line tool as an API, but you'd still have to construct string-like arguments. Is that enough? As for what the construction command line looks like, that's a lot more fluid - your exact use case might be useful to ensure I support that.

**Comment by snoyberg** [comment]
Yeah, I'm fine with that. I realize it's _almost_ the same as us just calling the executable directly, but bundling it as a library means we only have to worry about a single executable (our cron job that generates databases), and therefore don't need to worry about keeping two separate executables in sync.

I'm not opposed to a richer API for creating databases in the future, but I can definitely get started with that.

**Comment by ndmitchell** [comment]
Yep, that makes sense. I'll write some docs about how to generate databases, and then point you at them, and you can see if it's enough or not.

**Comment by snoyberg** [comment]
That's great, thank you!

**Comment by ndmitchell** [comment]
Docs now written, in particular I think you'll be after [building a database from a directory](https://github.com/ndmitchell/hoogle/blob/master/docs/Install.md#index-a-directory). A few notes:

* It looks at a directory and expects `.txt` files in there. You will probably have to unpack all the files into a temp dir.
* It currently won't look for nearby `.cabal` files, which means it won't build a popularity index to get the best results first, and it won't let you search by author. I imagine these are features you will want. If the rest looks good, I'll look for nearby `.cabal` files.
* Would you prefer all the files to be sourced from two `.tar.gz` files? That's a possible option since that's what I do for normal Hoogle.

**Comment by snoyberg** [comment]
I can look into this a bit myself, but mentioning here in case you know offhand. When generating a Hoogle database via the commandline, everything works just fine, and I get a `foo.hoo` file. However, when I pass the exact same arguments to the API, I instead get a 0-lengthed `foo.hoo.gz` file generated.

**Comment by ndmitchell** [comment]
I just tried it, and it seems to be working as I expected. What arguments are you passing?

**Comment by snoyberg** [comment]
I was about to write back: I think you can ignore me, there seems to have been some other complication going on within my code base. Sorry for the noise.

**Comment by snoyberg** [comment]
Conversion complete, now to test it :)

https://github.com/fpco/stackage-server/compare/hoogle5?expand=1

Thanks Neil!

**Comment by ndmitchell** [comment]
Cool. For info, `is:exact` will do an exact search. I never understood that requirement though, especially now Hoogle always puts exact results first.

**Comment by ndmitchell** [comment]
And it would be good to have a list of what you consider blockers for switching over, and useful enhancements for after switching.

**Comment by snoyberg** [comment]
I don't think we have any blockers, @chrisdone was going to test out my changes this coming week and then we'll likely deploy. Thanks for the quick responses here, it really made it easy to make the change.

Question for ongoing maintenance: is the database format going to change over time? If so, is there some way for us to be aware of such changes so we can regenerate the database?

**Comment by ndmitchell** [comment]
The database is going to change with each fresh release (or might). Hopefully database generation is quick (a minute) thus on upgrade you can regen all databases. For the standard Hoogle I embed the version number in the file name by default. I realise that logic is tied to making actual releases, which. I intend to do shortly!

**Comment by snoyberg** [comment]
We want to do Hoogle database generation in batch on our build server and make it available to all of the frontend webservers hosting stackage.org. The way we do this today is upload each database to S3 with a file path encoding the Hoogle version and LTS/nightly snapshot name. If going forward each new Hoogle release that changes DB formats also bumps the version number, everything will naturally transition for us.

**Comment by ndmitchell** [comment]
Sounds good to me - although how were you expecting I changed the format of the DB without changing the code?

**Comment by snoyberg** [comment]
I meant while we're still tracking the github repository and presumably the
version number isn't changing.

**Comment by ndmitchell** [comment]
Hopefully you can move to real releases very soon - once you give me a list of what is critically broken I'll release once that pile is sorted. If there's nothing on the critically broken list, I'll release in the next few days.

**Comment by chrisdone** [comment]
@ndmitchell You're going to release Hoogle 5 soon? 😮 🙏

**Comment by snoyberg** [comment]
OK, issue that popped up on the build server:

```
/home/michael/stackage-server/.stack-work/install/x86_64-linux/lts-5.15/7.10.3/share/x86_64-linux-ghc-7.10.3/hoogle-5.0/misc/settings.txt: openFile: does not exist (No such file or directory)
```

It would be nice if the settings.txt file was either optional, or its contents were just read in via TH at compile time, to make deployment easier. I'll check out the codebase on this myself now.

**Comment by ndmitchell** [comment]
@chrisdone - yeah, hope is to polish up the immediate issues, deploy it at `$WORK`, then make it the official release. I was hoping for the end of the week just finished, but maybe next week. Happy to wait a little if any FP Complete things crop up though.

**Comment by chrisdone** [comment]
Great! Wanted to confirm because the answer dictates how I'll implement
"stack hoogle", ie clone the git repo or install from hackage for hoogle5.

**Comment by ndmitchell** [comment]
Definitely install from Hackage. If it ends up being a bottleneck on your side let me know, I'll just release as-is immediately.

**Comment by chrisdone** [comment]
Okay, I'll implement the feature with `stack build hoogle-5.x.x` as the install procedure.

**Comment by chrisdone** [comment]
@ndmitchell One thing that we need for stackage is the version of the package for a result. Current results don't contain a package version, so it's not possible to link to the haddocks of the correct version of the package. For the hoogle.org case this is okay, but for stackage.org where you can switch between LTS/nightly snapshots, we need to link to the specific version.

I'd started to make a patch on hoogle5 locally to add this, but it seems like a non-trivial schema update to the database. Would I put that information in `Modules`, `Packages` or a new `PackageVersions`  entry? As I progressed through the codebase it seemed less and less obvious I would produce a PR that you'd accept. 

In Stackage's own databases we have this information (so [I wrote a redirect](https://github.com/fpco/stackage-server/pull/180/commits/cb93e5472974a19eaecb9c580d1993004111294d) so that going to `/lts-x.y/text/Data-Text.html` redirects to `/lts-x.y/text-a.b.c/Data-Text.html`), but this is a bit of a trick. Loading up a map of package names to versions in the `/hoogle` page and then hoisting in the versions there is another option. Seems like retrofitting information that we'd ideally have right in the results, though.

Thoughts?

**Comment by ndmitchell** [comment]
Is package version enough? Won't the docs for foo-1.0 potentially change between LTS versions, if one of their dependencies changes, and it reexports stuff?

I would have thought you could put this information in package url quite handily, since it really is where you want to link to, so it fits the purpose. If we added a `--hackage` argument to `generate`, and you did `generate --hackage=https://stackage.org/lts-6.1/` would that be sufficient?

**Comment by chrisdone** [comment]
> Is package version enough? Won't the docs for foo-1.0 potentially change between LTS versions, if one of their dependencies changes, and it reexports stuff?

Right, in our case we know the LTS version, but not the package versions (off-hand). Example link: 

    https://www.stackage.org/haddock/lts-6.3/path-0.5.7/Path.html
                                                                ^ got it    ^ need it

I made a workaround to redirect the below to the above:

    https://www.stackage.org/haddock/lts-6.3/path/Path.html

But having the info right there in the result would be good.

> I would have thought you could put this information in package url quite handily, 

I couldn't find a simple place in the codebase where I could recover the package version from. Where can it be added?

> since it really is where you want to link to, so it fits the purpose. If we added a `--hackage` argument to `generate`, and you did `generate --hackage=https://stackage.org/lts-6.1/` would that be sufficient?

Yeah, that'd be sufficient for the first part (generating the snapshot version), we'd still be missing package versions.

In the [codebase we have](https://github.com/fpco/stackage-server/blob/cb93e5472974a19eaecb9c580d1993004111294d/Handler/Hoogle.hs#L169) to construct the URL:

``` haskell
                                  (haddockUrl
                                       snapshot
                                       (T.pack pname)
                                       (T.pack mname))))
```

But `haddockUrl` is supposed to take a `packagename-version` string.

What do you recommend?

**Comment by ndmitchell** [comment]
Is a redirect from https://www.stackage.org/haddock/lts-6.3/path to https://www.stackage.org/haddock/lts-6.3/path-0.5.7 that horrible? I could imagine 3rd party documentation tools that would make use of that redirect too. In general, if I have have a `foo-1.0` in a path component, I add a `foo` that redirects to the most recent `foo-1.0`. e.g. I'd also expect `https://www.stackage.org/haddock/lts/path` to take me there.

I also note that https://www.stackage.org/haddock/lts-6.3/path-0.5.7 doesn't work and that all of these things redirect to `s3.amazon`, which doesn't give a good user experience.

I appreciate all that is a bit of a hack, but really doing the `haddockUrl` at view time, rather than generate time, is the real hack. The entryUrl, or at least the moduleUrl/packageUrl, should be the things being used to produce the Url. Having packageUrl be https://www.stackage.org/haddock/lts-6.3/path-0.5.7 seems like a reasonable way of encoding that information.

**Comment by chrisdone** [comment]
Okay, we're going ahead with the redirect and deploying to see how that looks. We can hold off discussion about making any changes to hoogle itself. Cheers!

**Comment by chrisdone** [comment]
@ndmitchell Are you in a position to release hoogle5? What're the steps necessary before it can be up on Hackage? 😄

**Comment by ndmitchell** [comment]
I was hoping to do a bunch of stuff. That hasn't happened. Hey ho, will release as is - probably tomorrow night (looking at my current calendar).

**Comment by chrisdone** [comment]
Great! I'm implementing `stack hoogle` again with this in mind - similar to `stack build intero-x.y.z` it'll `stack build hoogle-x.y.z` to locally build the version known to be compatible if hoogle isn't in the PATH or the numeric-version is <5.

**Comment by ndmitchell** [comment]
Sounds good. I've raised #170 to make the release, and am closing this since there is a library. Please open whatever tickets for features you need (anything raised in the next 24 hours might even make the release - but I'm happy to release frequently afterwards too.)
