### ISSUE TITLE
Ambiguous module name Network.URI

### ISSUE THREAD

**Issue by rudes** [ndmitchell/hoogle#181]
When building from `cabal install hoogle` i get the following error:

Preprocessing library hoogle-5.0.2...

src/General/Web.hs:33:8:
    Ambiguous module name `Network.URI':
      it was found in multiple packages:
      network-uri-2.6.1.0 network-2.4.1.2
cabal: Error: some packages failed to install:
hoogle-5.0.2 failed during the building phase. The exception was:
ExitFailure 1

Was able to resolve by editing hoogle.cabal and changing both packages to < 2.6
https://github.com/ndmitchell/hoogle/blob/master/hoogle.cabal#L65-L66
network < 2.6,
network-uri < 2.6,

then i ran `cabal install network-uri-2.5.0.0` and had no build issues.
(see: https://hackage.haskell.org/package/network-uri-2.6.1.0)

**Comment by ndmitchell** [comment]
A better solution is to upgrade to both > 2.6 if you can. There's some convoluted logic at the top of https://hackage.haskell.org/package/network-uri which alegedly solves it all, but I had hoped it wasn't necessary. My temptation is to mark both >= 2.6, but I think I had that originally, and it lead to other problems...

**Comment by rudes** [comment]
I started out with >= 2.6 but got some other errors, i can't remember what they were right now. i'll attempt them in a minute and update.

**Comment by glguy** [comment]
Please add a network >= 2.6 constraint, people are asking for help in #haskell as they try to understand the conflict. with network-uri being incompatible with previous versions.

**Comment by hvr** [comment]
@ndmitchell  Well, the one combination that *must* be avoided at all costs is the combination of `network < 2.6 && network-uri >= 2.6`. So if `network < 2.6` is to remain supported, that  flag-conditional logic is really the only way to achieve this currently (btw, I don't think it can be avoided to use flags to express either-or constraints involving multiple packages for technical reasons, since we'll always need a symbolic name to refer to this choice for freezing-purposes - but that's another topic). 

If we were to split of network/network-uri today, we'd do it differently, and avoid requiring from every use-site requiring those conditionals.

That being said, I've hacked up

  http://hackage.haskell.org/package/network-uri-flag-0.1

I'd suggest to use that in future `hoogle` releases. I'll look into making it possible in hackage-server to retrofit `network-uri-flag` dependencies in older releases.

**Comment by ndmitchell** [comment]
I've done the magic dance in the Cabal file and released 5.0.3, so hopefully that fixes it. Hindsight is always a great thing, but unfortunately it's too difficult to rewrite history with such packaging decisions. Nice idea of network-uri-flag, but I copied in all the flags now.
